apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: lab-deploy
  template:
    metadata:
      labels:
        app: lab-deploy
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
